export const courseGroups = {
  English: [
    "English I",
    "AP Seminar – English",
    "Seminar/English",
    "English: African Literature",
    "English: World Literature",
    "AP Language and Composition",
    "AP Literature and Composition",
    "AP Research",
  ],
  "Social Sciences": [
    "Human Geography (Gr 9)",
    "World Civilizations (Gr 10)",
    "Economics",
    "US History",
    "Business Studies",
    "Global Issues",
    "Model United Nations (MUN)",
    "AP Psychology",
    "AP Comparative Government and Politics",
    "AP Economics: Macro & Micro",
    "AP Macroeconomics",
    "AP Microeconomics",
    "AP World History: Modern",
    "AP United States Government and Politics",
    "AP United States History",
    "AP European History",
    "AP Human Geography",
    "AP Research",
  ],
  "Foreign Languages": [
    "French (Beginning)",
    "French (Intermediate)",
    "French (Upper Intermediate)",
    "French (Advanced)",
    "AP French Language and Culture",
    "Spanish (Beginning)",
    "Spanish (Intermediate)",
    "Spanish (Upper Intermediate)",
    "Spanish (Advanced)",
    "AP Spanish Language and Culture",
    "AP Literature Language and Culture",
    "French Literature",
    "Spanish Literature",
    "AP Chinese Language and Culture",
    "AP German Language and Culture",
    "AP Italian Language and Culture",
    "AP Japanese Language and Culture",
  ],
  Mathematics: [
    "Algebra I",
    "Geometry",
    "Algebra II",
    "Statistics",
    "AP Precalculus",
    "AP Calculus AB",
    "AP Calculus BC",
    "AP Statistics",
  ],
  Science: [
    "Integrated Science I",
    "Integrated Science II",
    "Forensic Science",
    "Advanced Biology",
    "Advanced Chemistry",
    "Advanced Physics",
    "Advanced Environmental Science",
    "AP Biology",
    "AP Chemistry",
    "AP Physics I",
    "AP Physics II",
    "AP Physics C: Mechanics",
    "AP Physics C: Electricity and Magnetism",
    "AP Environmental Science",
    "AP Computer Science A",
    "AP Computer Science Principles",
    "Intro to Computer Science: Python",
  ],
  Arts: [
    "AP Studio Art: Drawing",
    "AP Studio Art: 2-D Design",
    "AP Studio Art: 3-D Design",
    "AP Art History",
    "AP Music Theory",
  ],
} as const;

export type CourseCategory = keyof typeof courseGroups;
export type Course = (typeof courseGroups)[CourseCategory][number];
